import { ApiError, RateLimitError } from "./errors";

/**
 * Client configuration. Sensitive values (tokens) are read from config or
 * environment variables rather than being hardcoded.
 */
export interface SpaceTradersConfig {
  /** The base URL of the API. Defaults to the public SpaceTraders v2 endpoint. */
  baseUrl?: string;
  /**
   * Agent bearer token: config takes precedence, then the `AGENT_TOKEN`
   * environment variable, otherwise an error is thrown.
   */
  token?: string;
  /** A custom fetch implementation (used to mock requests in tests). */
  fetch?: typeof fetch;
  /** Extra request headers; the User-Agent header is merged on top. */
  headers?: Record<string, string>;
}

export interface RequestOptions {
  path: string;
  /** Path parameters, e.g. `{ shipSymbol }`, which are substituted into the path. */
  params?: Record<string, string | number>;
  /** Query parameters; `undefined` values are dropped. */
  query?: Record<string, string | number | boolean | undefined>;
  /** The JSON request body. */
  body?: unknown;
}

/**
 * Thin HTTP layer around `fetch`. It handles URL construction, authentication
 * header injection, rate limiting, retries, and error mapping.
 *
 * "How to call an API" (auth, rate limiting, error handling) is a
 * cross-endpoint concern -> hand-written.
 * "Which API to call, what the parameters are, what the response looks like" ->
 * generated by the compiler in the future.
 */
export class HttpClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;
  private readonly extraHeaders: Record<string, string>;
  private readonly token: string;
  private lastRequestTime = 0;
  private readonly minRequestGapMs = 500; // API rate limit: 2 requests per second

  constructor(config: SpaceTradersConfig) {
    if (!config.token) {
      const env = process.env.AGENT_TOKEN;
      if (!env) {
        throw new Error(
          "SpaceTraders token required: pass config.token or set the AGENT_TOKEN environment variable",
        );
      }
      config.token = env;
    }
    this.baseUrl = (config.baseUrl ?? "https://api.spacetraders.io/v2").replace(/\/$/, "");
    this.fetchImpl = config.fetch ?? fetch;
    this.extraHeaders = config.headers ?? {};
    this.token = config.token;
  }

  /**
   * Build a fully-resolved URL from a path, path parameters, and query
   * parameters.
   */
  buildUrl(path: string, params?: Record<string, string | number>, query?: RequestOptions["query"]): string {
    let url = this.baseUrl + this.expandPath(path, params);
    if (query) {
      const qs = new URLSearchParams(
        Object.entries(query)
          .filter(([, v]) => v !== undefined && v !== null)
          .map(([k, v]) => [k, String(v)]),
      ).toString();
      if (qs) url += `?${qs}`;
    }
    return url;
  }

  private expandPath(path: string, params?: Record<string, string | number>): string {
    return path.replace(/\{(\w+)\}/g, (_match, key) => {
      const value = params?.[key];
      if (value === undefined) {
        throw new Error(`Missing path parameter "${key}" for path "${path}"`);
      }
      return encodeURIComponent(String(value));
    });
  }

  /**
   * Rate limit guard: ensures at least 500ms between consecutive requests
   * (the SpaceTraders API is limited to 2 requests per second).
   */
  private async respectRateLimit(): Promise<void> {
    const now = Date.now();
    const elapsed = now - this.lastRequestTime;
    if (elapsed < this.minRequestGapMs) {
      await new Promise((resolve) => setTimeout(resolve, this.minRequestGapMs - elapsed));
    }
    this.lastRequestTime = now;
  }

  /** Send a request and return a unified `{ ok, data, error }` shape. */
  async send<T>(options: RequestOptions & { method?: string }): Promise<ApiResponse<T>> {
    await this.respectRateLimit();
    const url = this.buildUrl(options.path, options.params, options.query);
    const method = options.method ?? "POST";
    const init: RequestInit = {
      method,
      headers: {
        "Content-Type": "application/json",
        "User-Agent": "spacetraders-api-demo/0.1.0",
        "Authorization": `Bearer ${this.token}`,
        ...this.extraHeaders,
      },
    };
    if (options.body !== undefined && options.body !== null) {
      init.body = JSON.stringify(options.body) as string;
    } else {
      init.body = "{}"; // The API rejects an empty string body for POST
    }

    let res: Response;
    try {
      res = await this.fetchImpl(url, init);
    } catch (e) {
      return { ok: false, error: new ApiError(0, null, `Network error: ${(e as Error).message}`) };
    }

    const raw = await res.text();
    const data = raw ? JSON.parse(raw) : undefined;

    if (!res.ok) {
      if (res.status === 429) {
        const ms = Math.round(parseFloat(res.headers.get("Retry-After") ?? "0") * 1000) + 100;
        return { ok: false, error: new RateLimitError(null, ms) };
      }
      const message = data?.error?.message ?? data?.message ?? res.statusText ?? "Request failed";
      return { ok: false, error: new ApiError(res.status, data, message) };
    }
    return { ok: true, data: data as T };
  }

  get<T>(options: RequestOptions & { method?: "GET" }): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "GET" });
  }

  post<T>(options: RequestOptions & { method?: "POST" }): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "POST" });
  }
}

/** A successful or failed response from HttpClient. */
export type ApiResponse<T> =
  | { ok: true; data: T }
  | { ok: false; error: ApiError };
