import { ApiError, RateLimitError } from "./errors";

/**
 * Client configuration. Sensitive values (tokens) are read from config or
 * environment variables rather than being hardcoded.
 */
export interface SpaceTradersConfig {
  /** The base URL of the API. Defaults to the public SpaceTraders v2 endpoint. */
  baseUrl?: string;
  /**
   * Agent bearer token: config takes precedence, then the `AGENT_TOKEN`
   * environment variable, otherwise an error is thrown.
   */
  token?: string;
  /** A custom fetch implementation (used to mock requests in tests). */
  fetch?: typeof fetch;
  /** Extra request headers; the User-Agent header is merged on top. */
  headers?: Record<string, string>;
  /** Retry a rate-limited (429) response up to this many times. */
  maxRetries?: number;
  /** Exponential backoff multiplier applied per 429 retry. */
  backoffMultiplier?: number;
}

export interface RequestOptions {
  path: string;
  /** Path parameters, e.g. `{ shipSymbol }`, which are substituted into the path. */
  params?: Record<string, string | number>;
  /** Query parameters; `undefined` values are dropped. */
  query?: Record<string, string | number | boolean | undefined>;
  /** The JSON request body. */
  body?: unknown;
}

/**
 * Thin HTTP layer around `fetch`. It handles URL construction, authentication
 * header injection, rate limiting, retries, and error mapping.
 *
 * "How to call an API" (auth, rate limiting, error handling) is a
 * cross-endpoint concern -> hand-written.
 * "Which API to call, what the parameters are, what the response looks like" ->
 * generated by the compiler in the future.
 */
export interface HttpClientOptions {
  /** Maximum number of retries on a 429 response before giving up. */
  maxRetries?: number;
  /** Base backoff multiplier applied per retry (default 2). */
  backoffMultiplier?: number;
}

export class HttpClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;
  private readonly extraHeaders: Record<string, string>;
  private readonly token: string;
  private readonly maxRetries: number;
  private readonly backoffMultiplier: number;
  private lastRequestTime = 0;
  private readonly minRequestGapMs = 500; // API rate limit: 2 requests per second

  constructor(config: SpaceTradersConfig) {
    if (!config.token) {
      const env = process.env.AGENT_TOKEN;
      if (!env) {
        throw new Error(
          "SpaceTraders token required: pass config.token or set the AGENT_TOKEN environment variable",
        );
      }
      config.token = env;
    }
    this.baseUrl = (config.baseUrl ?? "https://api.spacetraders.io/v2").replace(
      /\/$/,
      "",
    );
    this.fetchImpl = config.fetch ?? fetch;
    this.extraHeaders = config.headers ?? {};
    this.token = config.token;
    this.maxRetries = config.maxRetries ?? 3;
    this.backoffMultiplier = config.backoffMultiplier ?? 2;
  }

  /**
   * Build a fully-resolved URL from a path, path parameters, and query
   * parameters.
   */
  buildUrl(
    path: string,
    params?: Record<string, string | number>,
    query?: RequestOptions["query"],
  ): string {
    let url = this.baseUrl + this.expandPath(path, params);
    if (query) {
      const qs = new URLSearchParams(
        Object.entries(query)
          .filter(([, v]) => v !== undefined && v !== null)
          .map(([k, v]) => [k, String(v)]),
      ).toString();
      if (qs) url += `?${qs}`;
    }
    return url;
  }

  private expandPath(
    path: string,
    params?: Record<string, string | number>,
  ): string {
    return path.replace(/\{(\w+)\}/g, (_match, key) => {
      const value = params?.[key];
      if (value === undefined) {
        throw new Error(`Missing path parameter "${key}" for path "${path}"`);
      }
      return encodeURIComponent(String(value));
    });
  }

  /**
   * Rate limit guard: ensures at least 500ms between consecutive requests
   * (the SpaceTraders API is limited to 2 requests per second).
   */
  private async respectRateLimit(): Promise<void> {
    const now = Date.now();
    const elapsed = now - this.lastRequestTime;
    if (elapsed < this.minRequestGapMs) {
      await new Promise((resolve) =>
        setTimeout(resolve, this.minRequestGapMs - elapsed),
      );
    }
    this.lastRequestTime = now;
  }

  /**
   * Send a request and return a unified `{ ok, data, error }` shape.
   *
   * Retries on HTTP 429 (rate limit) up to `maxRetries` times, backing off by
   * `Retry-After` (or an exponential default) doubled each attempt. A 429 that
   * survives all retries is returned as a single `RateLimitError`.
   */
  async send<T>(
    options: RequestOptions & { method?: string },
  ): Promise<ApiResponse<T>> {
    let attempt = 0;
    // Exponential base backoff; overridden by a server-provided Retry-After.
    let backoffMs = 250;
    for (;;) {
      await this.respectRateLimit();
      const url = this.buildUrl(options.path, options.params, options.query);
      const method = options.method ?? "POST";
      const init: RequestInit = {
        method,
        headers: {
          "Content-Type": "application/json",
          "User-Agent": "spacetraders-api-demo/0.1.0",
          Authorization: `Bearer ${this.token}`,
          ...this.extraHeaders,
        },
      };
      if (options.body !== undefined && options.body !== null) {
        init.body = JSON.stringify(options.body) as string;
      }
      // Note: For GET requests, body is undefined - the API may reject a body

      let res: Response;
      try {
        res = await this.fetchImpl(url, init);
      } catch (e) {
        return {
          ok: false,
          error: new ApiError(0, null, `Network error: ${(e as Error).message}`),
        };
      }

      // Rate limited: back off and retry while attempts remain.
      if (res.status === 429 && attempt < this.maxRetries) {
        const retryAfter = parseFloat(res.headers.get("Retry-After") ?? "") || 0;
        const waitMs = retryAfter
          ? Math.round(retryAfter * 1000) + 100
          : backoffMs;
        attempt++;
        backoffMs *= this.backoffMultiplier;
        await this.delay(waitMs);
        continue;
      }

      const raw = await res.text();
      const data = raw ? JSON.parse(raw) : undefined;

      // SpaceTraders wraps successful responses in a `{ data: <payload>, meta }`
      // envelope. Unwrap one level so callers receive the actual payload (e.g. an
      // `Agent` instance) rather than the wrapper. Endpoints that return a flat
      // object (like `GET /`) have no `data` field and are returned as-is.
      const unwrapped =
        data && typeof data === "object" && "data" in data
          ? (data as { data: unknown }).data
          : data;

      if (!res.ok) {
        const message =
          data?.error?.message ??
          data?.message ??
          res.statusText ??
          "Request failed";
        if (res.status === 429) {
          return { ok: false, error: new RateLimitError(null, 0) };
        }
        return { ok: false, error: new ApiError(res.status, data, message) };
      }
      return { ok: true, data: unwrapped as T };
    }
  }

  /** Sleep for `ms` milliseconds. */
  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  get<T>(
    options: RequestOptions & { method?: "GET" },
  ): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "GET" });
  }

  post<T>(
    options: RequestOptions & { method?: "POST" },
  ): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "POST" });
  }

  put<T>(
    options: RequestOptions & { method?: "PUT" },
  ): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "PUT" });
  }

  patch<T>(
    options: RequestOptions & { method?: "PATCH" },
  ): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "PATCH" });
  }

  delete<T>(
    options: RequestOptions & { method?: "DELETE" },
  ): Promise<ApiResponse<T>> {
    return this.send<T>({ ...options, method: "DELETE" });
  }
}

/** A successful or failed response from HttpClient. */
export type ApiResponse<T> =
  | { ok: true; data: T }
  | { ok: false; error: ApiError };

/**
 * Client specifically for AgentToken auth scheme.
 * Enforces usage of AgentToken (AGENT_TOKEN env var or config.token).
 */
export class AgentTokenClient extends HttpClient {
  constructor(config?: SpaceTradersConfig) {
    if (!config?.token && !process.env.AGENT_TOKEN) {
      throw new Error(
        "AgentTokenClient requires AGENT_TOKEN or config.token (AgentToken scheme)",
      );
    }
    super(config ?? {});
  }
}

/**
 * Client specifically for AccountToken auth scheme.
 * Enforces usage of AccountToken (ACCOUNT_TOKEN env var or config.accountToken).
 */
export class AccountTokenClient extends HttpClient {
  constructor(
    config?: { accountToken?: string } & Omit<SpaceTradersConfig, "token">,
  ) {
    const token = config?.accountToken || process.env.ACCOUNT_TOKEN;
    if (!token) {
      throw new Error(
        "AccountTokenClient requires ACCOUNT_TOKEN or config.accountToken (AccountToken scheme)",
      );
    }
    super({ ...config, token });
  }
}
